trigger:
- develop  # Defina a branch da qual você deseja acionar o pipeline

pr: none  # Desative a compilação automática para pull requests

pool:
  vmImage: 'macos-latest'  # Escolha uma imagem de VM do macOS ou do Windows, dependendo do ambiente que você está direcionando

steps:
- script: |
    npm install
    npx expo start
  displayName: 'Compilar aplicativo Expo'

