trigger:
- develop  # Defina a branch da qual você deseja acionar o pipeline

pr: none 

pool:
  vmImage: 'macos-latest' 

steps:
- script: |
    # Instale a CLI do Expo
    npm install -g eas-cli

    # Instale as dependências do projeto
    npm install

    # Faça o login na sua conta Expo (opcional, necessário se você quiser publicar)
    expo login -u odavisilva -p arroz1234/

    # Execute o build do aplicativo com Expo
    eas build -p ios

    # Execute o build do aplicativo para Android
    eas build -p android
  displayName: 'Compilar aplicativo Expo'

- script: |
    # Faça o login na sua conta Expo (opcional, necessário se você quiser publicar)
    expo login -u odavisilva -p arroz1234/

    # Publique o aplicativo para a Expo
    expo publish
  displayName: 'Publicar aplicativo Expo'
