trigger:
- master

pool:
  vmImage: 'macOS-latest'

jobs:
- job: Build
  displayName: 'Publish Artifact'
  steps:
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      checkLatest: true
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)'
      artifactName: 'source-code'
    displayName: 'Publish Source Code'
