trigger:
- main  # Defina a branch da qual você deseja acionar o pipeline

pr: none  # Desative a compilação automática para pull requests

pool:
  vmImage: 'macos-latest'  # Escolha uma imagem de VM do macOS ou do Windows, dependendo do ambiente que você está direcionando

steps:
- script: |
    # Instale o eas-cli
    npm install -g eas-cli

    # Instale as dependências do projeto
    npm install

    # Faça o login na sua conta Expo
    eas-cli login -u joaoovictor -p Jvo_0304  # Substitua com suas credenciais

    # Execute o EAS Build para iOS
    eas-cli build --platform ios --profile production
  displayName: 'Compilar aplicativo Expo (iOS)'

- script: |
    # Faça o login na sua conta Expo
    eas-cli login -u joaoovictor -p Jvo_0304  # Substitua com suas credenciais

    # Execute o EAS Build para Android
    eas-cli build --platform android --profile production
  displayName: 'Compilar aplicativo Expo (Android)'
