trigger:
- master

pool:
  vmImage: 'macOS-latest'

jobs:
- job: Build
  displayName: 'Build and Publish Artifact'
  steps:
  - task: UseNode@1
    inputs:
      versionSpec: '14.x'
      checkLatest: true
  - script: |
      npm install -g expo-cli
      npm install
      expo build:ios -c
    displayName: 'Build iOS App'
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/ios/build'
      artifactName: 'ios-build'
    displayName: 'Publish iOS Build'
